### ISSUE TITLE
problems with NavigationToolbar2QT

### ISSUE THREAD

**Issue by nevesanjos** [viictorjs/Refrapy#1]
Hi, I am a non-experienced with python and I am struggling with your code. 

I am processing data by using Gimli, but I would like to use your code for picking the first arrivals.

I am doing a P.h.D. at the University of Wyoming,  just starting, but  I am Brazilian, from São Paulo. 

I have access to Geogiga, for example, but I would like to avoid using commercial Softwares.

**Comment by viictorjs** [comment]
Hello!

Glad to hear you are interested in the program!

I recently uploaded a video on YouTube about how to use the program. You can check it out here: https://youtu.be/6bXnMYBM-DU. 

The output of the picking program is a .gp file. In case you don't need to run a time-terms inversion and only need the picked times, you can open the file with a text editor and check all the picked data (first column is the reciever position, second column is the picked time and the "/xx.xxx" is the source position of the above data).

There is still no oficial documentation about the code itself.

**Comment by nevesanjos** [comment]
Hey @viictorjs,

I was able to run it. You could add some additional instructions in order to be able to use it, for example:

conda create -n py3.4 python=3.4
source activate py3.4
conda install numpy scipy matplotlib obspy

Then, run the Launcher.py 

Another thing: Apparently, there is an increasing interest in pyGIMLi (https://github.com/gimli-org/gimli) code. They have a code to do seismic refraction tomography. However, they don't have an interface to pick the first arrivals as your code has. It would be great if your code could write an output file in a readable format for their code (attached an example file). I am trying to incorporate it already... 

[koenigsee.txt](https://github.com/viictorjs/Refrapy/files/3854711/koenigsee.txt)

Would be also great if the Sispick could read the .pg format (Sometime we would like to continue picking an unfinished dataset pick).

Have you published it? I am going to present some results in AGU this year, and I would like to cite your work.

Thanks,
Felipe

**Comment by nevesanjos** [comment]
Probably you can improve it, but following is my modification to write the output file for gimli: 

`with open(arquivoSaida,'a') as arqpck:
                    
                        p=[]
                        s={}
                        r={}
                        for i in range(len(self.arquivos)): 

                            if(float(self.listSource[i]) not in p): 
                                p.append(float(self.listSource[i]))  
                                s.update({i:len(p)})                
                            else:
                                s.update({i:r[float(self.listSource[i])]}) 
                           
                            for key in self.picks[i].keys(): 
                                if(key not in p):            
                                    p.append(float(key))     
                                    r.update({float(key):len(p)})  
                                elif(key not in r.keys()):
                                    for j in range(len(self.arquivos)):
                                        print(j)
                                        if(float(key) == float(self.listSource[j])):
                                            r.update({float(key):s[j]}) 
                            

                        arqpck.write('%d # shot/geophone points\n'%(len(p)))
                        arqpck.write('#x	y\n')
                        for i in range(len(p)):                
                            arqpck.write('{} {}\n'.format(p[i],0))                       
                        k=0
                        for i in range(len(self.arquivos)):
                            k = k + len(self.picks[i])
                        arqpck.write('%d # measurements\n'%(k))
                        arqpck.write('#s	g	t\n')
                        for i in range(len(self.arquivos)):
                            for key in sorted(self.picks[i]):
                                arqpck.write('%d %d %f\n'%(s[i],r[key],(10**-3)*self.picks[i][key]))                             
                    arqpck.close()                    
                messagebox.showinfo('Refrapy - Sispick','Pick salvo')`

**Comment by viictorjs** [comment]
Sorry for the late reply. 

I haven't publishied it yet, but I inteend on doing so soon. By this time you can check out en expanded abstract I presented at a conference in Rio de Janeiro (https://sbgf.org.br/mysbgf/eventos/expanded_abstracts/16th_CISBGf/Preliminary%20results%20of%20Refrapy%20-%20an%20open-source%20program%20for%20seismic%20refraction%20data%20analysis.pdf). 

About making Refrapy able to work along with pyGIMLi, it's a great ideia! Thank you for your colaboration. I'll definitly check this implementation.

**Comment by PATRICKNGUESSAN** [comment]
Dear Sir,

I hope this message finds you well. My name is NGUESSAN KOUASSI JEAN PATRICK, and I am currently pursuing an M.Tech in Petroleum Engineering, focusing on seismic tomography. I am reaching out to inquire about a particular program that I believe could greatly benefit my research project.

As I delve deeper into my study on seismic tomography, I have come across Refrapy on GitHub, and I am intrigued by its potential relevance to my work. I am particularly interested in how Refrapy could assist me in analyzing seismic data and generating accurate tomographic images to enhance reservoir characterization and imaging, but the launcher did not exist in the file.

Could you please provide send me the file including  the launcher,  Additionally, I would appreciate any insights or recommendations on how can be effectively integrated into my research workflow to optimize results and achieve my academic goals.

Thank you for your time and assistance. I look forward to hearing from you soon and exploring how can contribute to the advancement of my research project.
