### ISSUE TITLE
incompatibility with pygimili 1.2.2?

### ISSUE THREAD

**Issue by marscfeng** [viictorjs/Refrapy#2]
Thanks for sharing this good package with others. This software is awesome. I come to report an issue with pygimili 1.2.2.

For tomography inversion, the software will stuck during the imaging phase and threw out errors
`Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/fcheng/opt/anaconda3/envs/pg/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "Refrainv.py", line 709, in tomo_invert
    spi = np.unique(ra.dataContainer("s"), return_inverse=False)
AttributeError: 'TravelTimeManager' object has no attribute 'dataContainer`

So, I guess these errors are caused by the incompatibility of the new pygimili (1.2.2) since I cannot install 1.0.12 on my MAC as recommended.

**Comment by viictorjs** [comment]
Hi @marscfeng 

Thank you for your interest in the project and for reporting this issue. 

The current version of the Refrainv code indeed relies on functions from pygimli 1.0.12 to run a tomography inversion, and the use of a new release would probably cause errors. An update around using the latest release from pygimli for that is definetly on my to do list.

**Comment by marscfeng** [comment]
Just made a few updates to work around this issue. I believe you guys will find a better solution once you're available. 
[Refrainv.py.TXT](https://github.com/viictorjs/Refrapy/files/6863699/Refrainv.py.TXT)
