### ISSUE TITLE
about running Refrapick

### ISSUE THREAD

**Issue by subenyu** [viictorjs/Refrapy#4]
i have already installed obspy, but when i run the Refrapick. i said that  no module named 'obspy'
Could you please how to modify it ?
Thank you very much！

**Comment by viictorjs** [comment]
Hi @subenyu 

Did you install the required dependencies using Anaconda? Like this:

conda create -n refrapy python=3.7.7
conda activate refrapy
conda install obspy
conda install -c gimli -c conda-forge pygimli=1.0.12

**Comment by subenyu** [comment]
Thank you very much and it is the problem of env. and i solve it.

**Comment by viictorjs** [comment]
Great to hear it! Closing this issue now.
